macro(embed_asset _VAR _FILE)
    if(EXISTS "${_FILE}")
        file(READ "${_FILE}" _e_hex HEX)
        string(LENGTH "${_e_hex}" _e_len)
        math(EXPR _e_bytes "${_e_len} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _e_arr "${_e_hex}")
        string(APPEND _EMBED_H "extern const unsigned char ${_VAR}_data[];\nextern const unsigned int ${_VAR}_size;\n")
        string(APPEND _EMBED_CPP "const unsigned char ${_VAR}_data[] = {${_e_arr}};\nconst unsigned int ${_VAR}_size = ${_e_bytes};\n\n")
    else()
        message(WARNING "Asset not found: ${_FILE}")
    endif()
endmacro()

macro(embed_finalize _DIR)
    file(MAKE_DIRECTORY "${_DIR}")
    file(WRITE "${_DIR}/embedded_assets.h" "${_EMBED_H}")
    file(WRITE "${_DIR}/embedded_assets.cpp" "${_EMBED_CPP}")
endmacro()
